In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [3]:
sent =['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'i am a good developer',
       'understand the meaning of words',
       'your videoas are good',]

In [4]:
#define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videoas are good']

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3458, 4255, 5517, 6593],
 [3458, 4255, 5517, 8353],
 [3458, 2511, 5517, 261],
 [5777, 4537, 9434, 7783, 5481],
 [5777, 4537, 9434, 7783, 8622],
 [2056, 3458, 9213, 5517, 349],
 [3033, 1681, 3414, 7783]]

In [7]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.utils import pad_sequences 
from tensorflow.keras.models import Sequential 

In [8]:
import  numpy as np 

In [9]:
sent_length=8 
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3458 4255 5517 6593]
 [   0    0    0    0 3458 4255 5517 8353]
 [   0    0    0    0 3458 2511 5517  261]
 [   0    0    0 5777 4537 9434 7783 5481]
 [   0    0    0 5777 4537 9434 7783 8622]
 [   0    0    0 2056 3458 9213 5517  349]
 [   0    0    0    0 3033 1681 3414 7783]]


In [10]:
dim=10 

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/krupalakshmana/Desktop/Deep Learning NLP/venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-06-28 17:27:29.011106: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2025-06-28 17:27:29.012483: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-06-28 17:27:29.013818: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-06-28 17:27:29.013990: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-06-28 17:27:29.014159: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bu

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

2025-06-28 17:28:25.791405: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step


array([[[-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [ 0.00139118,  0.02916134, -0.01430368, -0.01449798,
          0.01753202,  0.04445256, -0.01702784, -0.0348906 ,
         -0.04677124,  0.04362664],
        [-0.04472905, -0.02228842,  0.04322479, -0.01383655,
         -0.04993993, -0.02979701,  0.01844854,  0.03268058,
         -0.01716175,  0.03948801],
        [-0.0484852 , -0.03932879, -0.00693852,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3458, 4255, 5517, 6593], dtype=int32)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [-0.02517852,  0.04850585,  0.03330335,  0.03433137,
         -0.03110186, -0.03527297,  0.01446014,  0.0367004 ,
          0.03018875, -0.01925546],
        [ 0.00139118,  0.02916134, -0.01430368, -0.01449798,
          0.01753202,  0.04445256, -0.01702784, -0.0348906 ,
         -0.04677124,  0.04362664],
        [-0.04472905, -0.02228842,  0.04322479, -0.01383655,
         -0.04993993, -0.02979701,  0.01844854,  0.03268058,
         -0.01716175,  0.03948801],
        [-0.0484852 , -0.03932879, -0.00693852,  0.0